apps/front/models.py
from exts import db
import shortuuid
import enum
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash

class GenderEnum(enum.Enum):
    MALE=1
    FEMALE=2
    SECRET=3
    UNKNOW=4

class FrontUser(db.Model):
    __tablename__="front_user"
    id=db.Column(db.String(30),primary_key=True,default=shortuuid.uuid)
    telephone=db.Column(db.String(11),nullable=False,unique=True)
    username=db.Column(db.String(50),nullable=False)
    _password=db.Column(db.String(100),nullable=False)
    email=db.Column(db.String(50),unique=True)
    realname=db.Column(db.String(50))
    avatar=db.Column(db.String(100))
    signature=db.Column(db.String(100))
    gender=db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time=db.Column(db.DateTime,default=datetime.now)


    @property
    def password(self):
        return self._password
    @password.setter
    def password(self,raw_password):
        self._password=generate_password_hash(raw_password)
    def check_password(self,raw_password):
        return check_password_hash(self.password,raw_password)

apps/front/forms.py
from ..forms import BaseFrom
from wtforms import StringField
from wtforms.validators import regexp,EqualTo,ValidationError
from utils import zlcache

class SignupForm(BaseFrom):
    telephone=StringField(validators=[regexp(r'1[3578]\d{9}',message="请输入正确格式手机号码")])
    sms_captcha=StringField(validators=[regexp(r"\w{4}",message="请输入正确格式验证码")])
    username=StringField(validators=[regexp(r'.{2,20}',message="请输入正确格式用户名")])
    password=StringField(validators=[regexp(r'[0-9a-zA-Z_\.]{6,20}',message="请输入正确格式密码")])
    password2=StringField(validators=[EqualTo("password",message="两次输入密码不一致")])
    graph_captcha=StringField(validators=[regexp(r"\w{4}",message="请输入正确格式的图片验证码")])

    def validate_sms_captcha(self,field):
        if field.data!="1111":
            sms_captcha=field.data
            telephone=self.telephone.data
            sms_captcha_mem=zlcache.get(telephone)
            if not sms_captcha_mem or sms_captcha.lower()!= sms_captcha_mem.lower() :
                raise ValidationError(message="短信验证码错误")
    def validate_graph_captcha(self,field):
        if field.data != "1111":
            graph_captcha=field.data
            graph_captcha_mem=zlcache.get(graph_captcha.lower())
            if not graph_captcha_mem:
                raise ValidationError("图形验证码错误")

class SigninForm(BaseFrom):
    telephone = StringField(validators=[regexp(r'1[3578]\d{9}', message="请输入正确格式手机号码")])
    password = StringField(validators=[regexp(r'[0-9a-zA-Z_\.]{6,20}', message="请输入正确格式密码")])
    remember = StringField()

apps/common/views.py
from flask import Blueprint,request,make_response
from .forms import SMSCaptchaForm
from utils import restful
from utils import zlcache
from utils.captcha import Captcha
from io import BytesIO
bp=Blueprint("common",__name__,url_prefix="/c")

@bp.route("/")
def index():
    return "common index"

@bp.route("/sms_captcha/",methods=['POST'])
def sms_captcha():
    form=SMSCaptchaForm(request.form)
    if form.validate():
        telephone=form.telephone.data
        capt=Captcha.gene_text(number=4)
        # 发送验证码
        zlcache.set(telephone,capt)
        print("向手机{}发送验证码:{}".format(telephone,capt))
        return restful.success()
    else:
        return restful.params_error("手机号码格式有误")

@bp.route("/captcha/")
def graph_captcha():
    text,image=Captcha.gene_graph_captcha()
    zlcache.set(text.lower(),text.lower())
    out=BytesIO()
    image.save(out,"png")
    out.seek(0)
    resp=make_response(out.read())
    resp.content_type="image/png"
    return resp

apps/front/__init__.py
from .views import bp

apps/front/views.py
from flask import Blueprint,views,render_template,request,url_for,session
from .forms import SignupForm,SigninForm
from utils import restful
from .models import FrontUser
from exts import db
from utils import safeutils
import config
bp=Blueprint("front",__name__,url_prefix="")



@bp.route("/")
def index():
    return render_template("front/front_index.html")
@bp.route("/test/")
def test():
    return render_template("front/test.html")


class SignupView(views.MethodView):
    def get(self):
        return_to=request.referrer
        if return_to and return_to!=request.url and safeutils.is_safe_url(return_to):
            return render_template("front/front_signup.html",return_to=return_to)
        else:
            return render_template("front/front_signup.html")
    def post(self):
        form=SignupForm(request.form)
        if form.validate():
            #需要验证手机号码唯一
            telephone=form.telephone.data
            username=form.username.data
            password=form.password.data
            user=FrontUser(telephone=telephone,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            message=form.get_error()
            return restful.params_error(message=message)
class SigninView(views.MethodView):
    def get(self):
        return_to=request.referrer
        if return_to and return_to !=request.url and return_to!=url_for("front.signin") and safeutils.is_safe_url(return_to):
            return render_template("front/front_signin.html",return_to=return_to)
        else:
            return render_template("front/front_signin.html")
    def post(self):
        form=SigninForm(request.form)

        if form.validate():
            telephone=form.telephone.data
            password=form.password.data
            remember=form.remember.data
            user=FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent=True
                return restful.success()
            else:
                return restful.params_error(message="用户名或密码错误")
        else:
            return restful.params_error(message=form.get_error())





bp.add_url_rule("/signin/",view_func=SigninView.as_view("signin"))
bp.add_url_rule("/signup/",view_func=SignupView.as_view("signup"))

templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    {% include "common/_heads.html" %}

    {% block heads %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">知了课堂</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for("front.signin") }}">登录</a></li>
        <li><a href="{{ url_for("front.signup") }}">注册</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


{% block body %}

{% endblock %}

</body>
</html>

templates/front/front_index.html
{% extends "front/front_base.html" %}
{% block title %}首页{% endblock %}

{% block body %}
我是首页
{% endblock %}

templates/front/front_signbase.html
{%  from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>

    {% include "common/_heads.html" %}
   <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
</head>

<link rel="stylesheet" href="{{ static("front/css/front_signbase.css") }}">
<script src="{{ static("front/js/zlparam.js") }}"></script>
{% block head %}

{% endblock %}

<body>
    <div class="outer-box">
        <div class="logo-img">
            <a href="/"><img src="{{ static("common/images/zhiliao.jpg") }}" alt="logo"></a>
            <h2>{% block h2_block %}
            
            {% endblock %}</h2>
        </div>
        <div class="sign-box">


        {% block signbox %}
        
        {% endblock %}

        </div>


    </div>
<spans style="display: none" id="return-to-span">{{ return_to }}</spans>
</body>
</html>

templates/front/front_signin.html
{% extends "front/front_signbase.html" %}
{% from "common/_macros.html" import static %}
{% block title %}用户登录{% endblock %}
{% block h2_block %}知了用户登录{% endblock %}
{% block head %}
    <script src="{{ static("front/js/front_signin.js") }}"></script>
{% endblock %}
{% block signbox %}

               <div class="form-group">
                    <input type="text" class="form-control" id="telephone" name="telephone" placeholder="手机号码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" name="password">
                </div>
                <div class="check-box">
                <lable>
                    <input type="checkbox" name="remember" value="1">记住我
                </lable>
                </div>
                    <button id="submit-btn" class="btn btn-warning btn-block">立即登录</button>
                    <a href="{{ url_for("front.signup") }}">还没注册?立即注册</a>
                    <a href="#" style="float: right">找回密码</a>
{% endblock %}

templates/front/front_signup.html
{% extends "front/front_signin.html" %}
{%  from "common/_macros.html" import static %}
{% block title %}用户注册{% endblock %}
{% block head %}
    <script src="{{ static("front/js/front_signup.js") }}"></script>
{% endblock %}
{% block h2_block %}知了用户注册{% endblock %}
{% block signbox %}
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" id="telephone" name="telephone" placeholder="手机号码">
                    <span class="input-group-btn">
                        <button id="sms-captcha" class="btn btn-default">发送验证码</button>
                    </span>
                </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="短信验证码" name="sms_captcha">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="用户名" name="username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" name="password">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="确认密码" name="password2">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="请输入验证码" name="graph_captcha">
                        <span class="input-group-addon captcha-addon">
                            <img id="captcha-img" class="captcha-img" src="{{ url_for("common.graph_captcha") }}" alt="">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <button id="submit-btn" class="btn btn-warning btn-block">立即注册</button>
            </div>
{% endblock %}

templates/front/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试</title>
</head>
<body>
<a href="{{ url_for("front.signup") }}">注册</a>
</body>
</html>