apps/cms/models.py
from exts import db
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime

class CMSPermission(object):
    # 0. 所有权限
    ALL_PERMISSION=0b11111111
    # 1. 访问者权限
    VISITOR=       0b00000001
    # 2.管理帖子权限
    POSTER=        0b00000010
    # 3.管理评论权限
    COMMENTER=     0b00000100
    # 4.管理板块权限
    BOARDER=       0b00001000
    # 5.管理前台用户权限
    FRONTUSER=     0b00010000
    # 6.管理后台用户权限
    CMSUSER=       0b00100000
    # 7.管理后台管理员权限
    ADMINER=       0b01000000

cms_role_user=db.Table(
    "cms_role_user",
    db.Column("cms_role_id",db.Integer,db.ForeignKey("cms_role.id"),primary_key=True),
    db.Column("cms_user_id",db.Integer,db.ForeignKey("cms_user.id"),primary_key=True)
)

class CMSRole(db.Model):
    __tablename__="cms_role"
    id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    name=db.Column(db.String(50),nullable=False)
    desc=db.Column(db.String(300),nullable=False)
    create_time=db.Column(db.DateTime,default=datetime.now)
    permissions=db.Column(db.Integer,default=CMSPermission.VISITOR)
    #cmsrole.(users) 权限对应用户 参考表 (cms_role_user) , 回调自己 users.(roles) 希望获得对于权限
    users=db.relationship("CMSUser",secondary=cms_role_user,backref='roles')



class CMSUser(db.Model):
    __tablename__="cms_user"
    id=db.Column(db.Integer,primary_key=True,autoincrement=True)
    username=db.Column(db.String(50),nullable=False)
    _password=db.Column(db.String(100),nullable=False)
    email=db.Column(db.String(50),nullable=False)
    join_time=db.Column(db.DateTime,default=datetime.now)

    def __init__(self,username,password,email):
        self.username=username
        self.password=password
        self.email=email

    @property
    def password(self):
        return self._password
    @password.setter
    def password(self,raw_password):
        self._password=generate_password_hash(raw_password)
    def check_password(self,raw_password):
        return check_password_hash(self.password,raw_password)

    @property
    def permissions(self):
        if not self.roles:
            return 0
        all_permissions=0
        for role in self.roles:
            all_permissions|=role.permissions
        return all_permissions

    def has_permission(self,permission):
        return self.permissions & permission == permission
    @property
    def is_developer(self):
        return self.has_permission(CMSPermission.ALL_PERMISSION)

apps/cms/forms.py
from wtforms import StringField,IntegerField
from wtforms.validators import Email,Length,InputRequired,EqualTo,ValidationError
from ..forms import BaseFrom
from utils import zlcache
from flask import g

class loginForm(BaseFrom):
    email=StringField(validators=[Email(message="请输入争取到邮箱格式"),InputRequired(message="请输入邮箱")])
    password=StringField(validators=[Length(min=3,max=20,message="请输入正确格式的密码")])
    remember=IntegerField()
class ResetpwdForm(BaseFrom):
    oldpwd=StringField(validators=[Length(min=3,max=20,message="请输入正确格式旧密码")])
    newpwd=StringField(validators=[Length(min=3,max=20,message="请输入正确格式新密码")])
    newpwd2=StringField(validators=[EqualTo("newpwd")])

class ResetEmailForm(BaseFrom):
    email=StringField(validators=[Email("请输入正确格式的邮箱")])
    captcha=StringField(validators=[Length(min=6,max=6,message="请输入正确长度的验证码!")])

    def validate_captcha(self,field):
        captcha=field.data
        email=self.email.data
        captcha_cache=zlcache.get(email)
        if not captcha_cache or captcha_cache.lower()!=captcha.lower():
            raise ValidationError("邮箱验证码错误")
    def validate_email(self,field):
        email=field.data
        if g.cms_user.email==email:
            raise ValidationError("不能修改为相同的邮箱")

apps/cms/__init__.py
from .views import bp
import apps.cms.hooks

apps/cms/views.py
from flask import Blueprint,views,render_template,request,url_for,session,redirect,g,jsonify
from .forms import loginForm,ResetpwdForm,ResetEmailForm
from .models import CMSUser,CMSPermission
from .decorators import login_required,permission_required
import config
from exts import db,mail
from flask_mail import Message
from utils import restful
import string
import random
from utils import zlcache

bp=Blueprint("cms",__name__,url_prefix="/cms")
# from .hooks import before_request

@bp.route("/")
@login_required
def index():
    return render_template("cms/cms_index.html")

@bp.route("/email/")
def send_email():
    message=Message("测试",["office2012.rain@gmail.com"],"hello world !")
    mail.send(message)
    return "success"

@bp.route("/email_captcha/")
def email_captcha():
    email=request.args.get("email")
    if not email:
        return restful.params_error("请输入邮箱")
    source=list(string.ascii_letters)
    source.extend(map(lambda x:str(x),range(0,10)))
    captcha="".join(random.sample(source,6))
    zlcache.set(email,captcha)
    message=Message("验证码",[email],"您的验证码是:%s"%captcha)
    try:
        mail.send(message)
    except:
        return restful.server_error()
    return restful.success()

@bp.route("/logout/")
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for("cms.login"))
@bp.route("/profile/")
def profile():
    return render_template("cms/cms_profile.html")
@bp.route("/boards/")
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    return render_template("cms/cms_boards.html")
@bp.route("/comments/")
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template("cms/cms_comments.html")
@bp.route("/croles/")
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    return render_template("cms/cms_croles.html")
@bp.route("/fusers/")
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    return render_template("cms/cms_fusers.html")
@bp.route("/posts/")
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    return render_template("cms/cms_posts.html")
@bp.route("/cusers/")
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    return render_template("cms/cms_cusers.html")

class loginView(views.MethodView):
    def get(self,message=None):
        return render_template("cms/login.html",message=message)
    def post(self):
        form=loginForm(request.form)
        if form.validate():
            email=form.email.data
            password=form.password.data
            remember=form.remember.data
            user=CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID]=user.id
                if remember:
                    session.permanent=True
                return redirect(url_for("cms.index"))
            else:
                return self.get(message="用户名或密码错误")
        else:
            # print(form.errors)
            message=form.get_error()
            return self.get(message=message)
class ResetPwdView(views.MethodView):
    def get(self):
        return render_template("cms/cms_resetpwd.html")
    def post(self):
        form=ResetpwdForm(request.form)
        if form.validate():
            newpwd=form.newpwd.data
            oldpwd=form.oldpwd.data
            user=g.cms_user
            if user.check_password(oldpwd):
                user.password=newpwd
                db.session.commit()
                return restful.success()
            else:
                return restful.params_error("旧密码错误")
        else:
            return restful.params_error(form.get_error())
class ResetEmailView(views.MethodView):
    def get(self):
        return render_template("cms/cms_resetemail.html")
    def post(self):
        form=ResetEmailForm(request.form)
        if form.validate():
            g.cms_user.email=form.email.data
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(form.get_error())
bp.add_url_rule("/resetemail/",view_func=ResetEmailView.as_view("resetemail"))
bp.add_url_rule("/resetpwd/",view_func=ResetPwdView.as_view("resetpwd"))
bp.add_url_rule("/login/",view_func=loginView.as_view("login"))

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>
    {% include "common/_heads.html" %}
    <link rel="stylesheet" href="{{ static('cms/css/base.css') }}">
    <script src="{{ static('cms/js/base.js') }}"></script>



    {% block head %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Zhang_derek论坛管理后台</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">

                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                         <li><a href="{{ url_for("cms.profile") }}">个人信息</a></li>
                        <li><a href="{{ url_for("cms.resetpwd") }}">修改密码</a></li>
                        <li><a href="{{ url_for("cms.resetemail") }}">修改邮箱</a></li>
                    </ul>
                </li>


            {% set cms_user=g.cms_user %}

            {% if cms_user.has_permission(CMSPermission.POSTER) %}
                <li class="nav-group post-manage"><a href="{{ url_for("cms.posts") }}">帖子管理</a></li>
            {% endif %}

            {% if cms_user.has_permission(CMSPermission.COMMENTER) %}
                <li class="comments-manage"><a href="{{ url_for("cms.comments") }}">评论管理</a></li>
            {% endif %}

            {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                <li class="board-manage"><a href="{{ url_for("cms.boards") }}">板块管理</a></li>
            {% endif %}

            {% if cms_user.has_permission(CMSPermission.FRONTUSER) %}
                 <li class="nav-group user-manage"><a href="{{ url_for("cms.fusers") }}">前台用户管理</a></li>
            {% endif %}

            {% if cms_user.has_permission(CMSPermission.CMSUSER) %}
                <li class="nav-group cmsuser-manage"><a href="{{ url_for("cms.cusers") }}">CMS用户管理</a></li>
            {% endif %}

            {% if cms_user.is_developer %}
                <li class="cmsrole-manage"><a href="{{ url_for("cms.croles") }}">CMS组管理</a></li>
            {% endif %}

            </ul>
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/cms_base1.html
{% from "common/_macros.html" import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <style>
        .links>a{
            padding-left: 10px;
        }
    </style>
{% block head %}

{% endblock %}
</head>
<body>
<div style="display: flex" class="links">
<a href="{{ url_for("cms.profile") }}">个人信息</a>
<a href="{{ url_for("cms.resetpwd") }}">修改密码</a>

</div>
<p>用户名:{{ g.cms_user.username }}</p>
<a href="{{ url_for("cms.logout") }}">注销</a>

<h3>{% block page_title %}{% endblock %}</h3>

{% block page_content %}{% endblock %}

</body>
</html>

templates/cms/cms_boards.html
{% extends "cms/cms_base.html" %}

{% block title %}板块管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
板块管理界面
{% endblock %}

templates/cms/cms_comments.html
{% extends "cms/cms_base.html" %}

{% block title %}评论管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
评论管理界面
{% endblock %}

templates/cms/cms_croles.html
{% extends "cms/cms_base.html" %}

{% block title %}CMS组管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
CMS组管理界面
{% endblock %}

templates/cms/cms_cusers.html
{% extends "cms/cms_base.html" %}

{% block title %}CMS用户管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
CMS用户管理界面
{% endblock %}

templates/cms/cms_fusers.html
{% extends "cms/cms_base.html" %}

{% block title %}前台管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
前台管理界面
{% endblock %}

templates/cms/cms_index.html
{% extends "cms/cms_base.html" %}
{% block title %}
欢迎使用cms后台管理系统
{% endblock %}
{% block page_title %}
欢迎使用cms后台管理系统
{% endblock %}

templates/cms/cms_posts.html
{% extends "cms/cms_base.html" %}

{% block title %}帖子管理{% endblock %}

{% block head %}{% endblock %}

{% block page_title %}{{ self.title() }}{% endblock %}

{% block main_content %}
帖子管理界面
{% endblock %}

templates/cms/cms_profile.html
{% extends "cms/cms_base.html" %}
{% block title %}
个人信息
{% endblock %}
{% block page_title %}
个人信息
{% endblock %}
{% block main_content %}
    {% set user=g.cms_user %}
<table class="table table-bordered">
    <tbody>
    <tr>
        <td>用户名:</td>
        <td>{{ user.username }}</td>
    </tr>
    <tr>
        <td>邮箱</td>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <td>角色</td>
        <td>{% for role in user.roles %}
            {{ role.name }}
            {% if not loop.last %}，{% endif %}
        {% endfor %}
        </td>
    </tr>
    <tr>
        <td>权限</td>
        <td>{% for role in user.roles %}
            {{ role.desc }}
            {% if not loop.last %}；{% endif %}
        {% endfor %}
        </td>
    </tr>
    <tr>
        <td>加入时间</td>
        <td>{{ user.join_time }}</td>
    </tr>
    </tbody>
</table>
{% endblock %}

templates/cms/cms_resetemail.html
{% extends "cms/cms_base.html" %}
{% from "common/_macros.html" import static %}
{% block title -%}
修改邮箱
{%- endblock %}
{% block page_title -%}
{{ self.title() }}
{%- endblock %}
{% block head %}
    <script src="{{ static("cms/js/resetemail.js") }}"></script>
{% endblock %}
{% block main_content %}
    <div class="form-container">
        <form action="" method="post">
            <div class="form-group">
                <div class="input-group">
                    <input type="email" class="form-control" name="email" placeholder="请输入邮箱地址">
                    <span class="input-group-addon" id="captcha" style="cursor: pointer">获取验证码</span>
                </div>
            </div>
            <div class="form-group">
                <input type="text" name="captcha" class="form-control" placeholder="请输入验证码">
            </div>
            <div class="form-group">
                <button id="submit" class="btn btn-primary">立即修改</button>
            </div>

        </form>
    </div>

{% endblock %}

templates/cms/cms_resetpwd.html
{% extends "cms/cms_base.html" %}
{% from "common/_macros.html" import static %}
{% block title -%}
修改密码
{%- endblock %}

{% block head %}
    <script src="{{ static("common/zlajax.js") }}"></script>
    <script src=" {{ static("cms/js/resetpwd.js") }}"></script>
    <style>
    .form-continer{
        width: 390px;
    }
    </style>
{% endblock %}

{% block page_title -%}
{{ self.title() }}
{%- endblock %}

{% block main_content %}

    <div class="form-continer">

        <form action="" method="post">

             <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">旧密码</div>
            <input type="password" class="form-control" name="oldpwd" placeholder="请输入旧密码">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">新密码</div>
            <input type="password" class="form-control" name="newpwd" placeholder="请输入旧密码">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-addon">确认新密码</div>
            <input type="password" class="form-control" name="newpwd2" placeholder="请输入旧密码">
        </div>
    </div>
            <button id="submit" type="submit" class="btn btn-primary">修改密码</button>
        </form>



    </div>



{% endblock %}

templates/cms/login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>后台登录</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ url_for("static",filename="cms/css/login1.css") }}" rel="stylesheet">


  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post">
        <h2 class="form-signin-heading">请登录</h2>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" >
        <label for="inputEmail" class="sr-only">邮箱</label>
        <input type="email" id="inputEmail" name="email" class="form-control" placeholder="邮箱地址" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="密码" required>
        <div class="checkbox">
          <label style="display: flex">
            <input type="checkbox" name="remember" value="1"> 记住我
              {% if message %}
                <p class="text-danger">{{ message }}</p>
              {% endif %}
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">立即登录</button>
      </form>

    </div> <!-- /container -->



  </body>
</html>